# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daba911071d1c3ae920d61956b1f410056680886ff83cca7296d94fdcf5c87b0ac2e720bf998a8e557c96de7d12cbda1965725029dbdd39ea4575f4777fd36db

test:
  secret_key_base: 0ca5e5da26490c5f661bff9f8a08fa710c8fb9d9a8ef463e7253341d8fe1fa0faf22b84695b37642c9324fa0ebe105f29c6933ef300a063f7199b4d19503568b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
